<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/02/24 12:42:10

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=procaptcha',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
